customer/urls.py
from django.urls import path
from .views import UserRegistrationView, UserLoginView, UserProfileView, activate, ProfileUpdateView, change_pass, user_logout,AdminHomeView
urlpatterns = [
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('admin/', AdminHomeView.as_view(), name='admin_home'),
    path('change_pass/', change_pass, name='change_pass'),
    path('edit_profile/', ProfileUpdateView.as_view(), name='edit_profile'),
    path('active/<uid64>/<token>/', activate, name='activate'),
]

pet/urls.py
from django.urls import path
from .views import AddPetView, PetDetailView, AllPetView, PetEditView, PetDeleteView
urlpatterns = [
    path('all_pets/', AllPetView.as_view(), name="all_pets"),
    path('all_pets/<slug:category_slug>/',
         AllPetView.as_view(), name='category'),
    path('add_pet/', AddPetView.as_view(), name="add_pet"),
    path('edit_pet/<int:id>', PetEditView.as_view(), name="edit_pet"),
    path('pet_detail/<int:id>', PetDetailView.as_view(), name="pet_detail"),
    path('pet_delete/<int:id>', PetDeleteView.as_view(), name="pet_delete"),
]

pet_fair_bd/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, ContactView, AboutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('pet/',include('pet.urls')),
    path('',HomeView.as_view(),name='home'),
    path('contact',ContactView.as_view(),name='contact'),
    path('about',AboutView.as_view(),name='about'),
    path('transaction/',include('transaction.urls')),

]
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from . constants import GENDER
# Create your models here.
class Customer(models.Model):
    user=models.OneToOneField(User,related_name='customer',on_delete=models.CASCADE)
    customer_id=models.IntegerField(unique=True)
    gender=models.CharField(max_length=10,choices=GENDER)
    phone=models.CharField(max_length=13)
    balance = models.DecimalField(decimal_places=2,max_digits=12,default=0)
    street_address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    image=models.ImageField(upload_to='customer/images',null=True,blank=True)

    def __str__(self):
        return str(self.user)


class Contact(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField()
    content = models.TextField()

    def __str__(self):
        return self.name

transaction/models.py
from django.db import models
from .constants import TRANSACTION_TYPE
from customer .models import Customer
from pet .models import Pet
# Create your models here.


class Transaction(models.Model):
    customer = models.ForeignKey(
        Customer, related_name='transaction', on_delete=models.CASCADE)
    pet = models.ForeignKey(Pet, related_name='buy_pet',
                             on_delete=models.CASCADE, null=True, blank=True)
    amount = models.DecimalField(decimal_places=2, max_digits=12)
    balance_after_transaction = models.DecimalField(
        decimal_places=2, max_digits=12)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE)
    timestamps = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.customer.user.username)

customer/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Customer,Contact
from django.contrib.auth.forms import UserCreationForm
from .constants import GENDER


class UserRegistrationForm(UserCreationForm):
    phone = forms.CharField(max_length=12)
    gender = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect)
    street_address = forms.CharField(max_length=50)
    city = forms.CharField(max_length=50)
    country = forms.CharField(max_length=50)
    image=forms.ImageField()

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name',
                  'last_name', 'email', 'gender', 'street_address', 'city', 'country', 'image']

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            phone = self.cleaned_data.get('phone')
            gender = self.cleaned_data.get('gender')
            street_address = self.cleaned_data.get('street_address')
            city = self.cleaned_data.get('city')
            country = self.cleaned_data.get('country')
            image = self.cleaned_data.get('image')

            Customer.objects.create(
                user=user,
                customer_id=10000+user.id,
                phone=phone,
                gender=gender,
                street_address=street_address,
                city=city,
                country=country,
                image=image
            )
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class UserUpdateForm(forms.ModelForm):
    phone = forms.CharField(max_length=12)
    gender = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect)
    street_address = forms.CharField(max_length=50)
    city = forms.CharField(max_length=50)
    country = forms.CharField(max_length=50)
    image = forms.ImageField()

    class Meta:
        model=User
        fields = ["first_name", "last_name"]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance:
            try:
                customer = self.instance.customer
            except:
                customer = None

            if customer:
                self.fields['phone'].initial = customer.phone
                self.fields['gender'].initial = customer.gender
                self.fields['street_address'].initial = customer.street_address
                self.fields['city'].initial = customer.city
                self.fields['country'].initial = customer.country
                self.fields['image'].initial = customer.image

    def save(self, commit=True):
        user = super().save(commit=False)

        if commit:
            user.save()
            customer, created = Customer.objects.get_or_create(user=user)

            customer.phone = self.cleaned_data.get("phone")
            customer.gender = self.cleaned_data.get("gender")
            customer.street_address = self.cleaned_data.get("street_address")
            customer.city = self.cleaned_data.get("city")
            customer.country = self.cleaned_data.get("country")
            customer.image = self.cleaned_data.get("image")
            customer.save()

        return user


class ContactForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows': 3}))

    class Meta:
        model = Contact
        fields=['name','email','content']

customer/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, UserUpdateForm,ContactForm
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import logout, update_session_auth_hash
from django.db.models import Sum
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
from transaction.models import Transaction
from transaction.constants import BUY
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from .models import Customer,Contact
from django.contrib.auth.models import User
from pet .models import Pet
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from datetime import datetime
from django.utils.decorators import method_decorator
from django.views.generic import CreateView

class UserRegistrationView(FormView):
    template_name = 'customer/register.html'
    success_url = reverse_lazy('login')
    form_class = UserRegistrationForm

    def form_valid(self, form):
        user = form.save()
        
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        confirm_link = f"https://pet-fair-bd.onrender.com/customer/active/{uid}/{token}"
        email_subject="Confirm Your Email"
        email_body=render_to_string('customer/confirm_mail.html',{'confirm_link':confirm_link})
        email=EmailMultiAlternatives(email_subject,'',to=[user.email])
        email.attach_alternative(email_body,"text/html")
        email.send()

        messages.success(
            self.request, "Welcome! You have registered Successfully. Check your email to confirm your account."
        )

        login(self.request, user)

        return super().form_valid(form)


def activate(request, uid64, token):
    try:
        uid = urlsafe_base64_decode(uid64).decode()
        user = User._default_manager.get(pk=int(uid))
    except (TypeError, ValueError, OverflowError, User.DoesNotExist) as e:
        print(f"Activation Error: {e}")
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('profile')
    else:
        return redirect('register')
    
class UserLoginView(LoginView):
    template_name='customer/login.html'

    def get_success_url(self):
        if self.request.user.is_staff:
            messages.success(self.request, "Welcome Admin ")
            return reverse_lazy('admin_home')
        else:
            messages.success(self.request, "Welcome! You are successfully logged in.")
        return reverse_lazy('profile')


def user_is_admin(user):
    return user.is_authenticated and user.is_staff


@method_decorator(login_required(login_url='/customer/login'), name='dispatch')
@method_decorator(user_passes_test(user_is_admin, login_url='/customer/login'), name='dispatch')
class AdminHomeView(View):
    template_name = 'customer/admin_home.html'

    def get_queryset(self):
        queryset = Transaction.objects.all()
        self.balance = queryset.aggregate(Sum('amount'))['amount__sum']
        self.total = queryset.aggregate(Sum('amount'))['amount__sum'] or 0
        return queryset

    def get(self, request, *args, **kwargs):
        pets = Pet.objects.all()
        context = {
            'object_list': self.get_queryset(),
            'balance': self.balance,
            'total': self.total,
            'pets':pets,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        start_date_str = request.POST.get('start_date')
        end_date_str = request.POST.get('end_date')

        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date_str, '%Y-%m-%d').date()

            queryset = Transaction.objects.filter(
                timestamps__date__gte=start_date,
                timestamps__date__lte=end_date
            )
            self.balance = queryset.aggregate(Sum('amount'))['amount__sum']
            self.total = queryset.aggregate(Sum('amount'))['amount__sum'] or 0

            context = {
                'object_list': queryset,
                'balance': self.balance,
                'total': self.total,
            }

            return render(request, self.template_name, context)

        return redirect('admin_home')


@method_decorator(login_required, name='dispatch')
class UserProfileView(LoginRequiredMixin, View):
    template_name = "customer/profile.html"

    def get(self, request):
        form = UserUpdateForm(instance=request.user)
        pets=Pet.objects.filter(user=request.user)
        customer = self.request.user.customer
        transaction = Transaction.objects.filter(customer=self.request.user.customer)
        total = transaction.aggregate(
            total_price=Sum('amount')
        )['total_price'] or 0
        buy = Transaction.objects.filter(
            transaction_type=BUY, customer=self.request.user.customer)
        total_buy_price = buy.aggregate(
            total_price=Sum('amount')
        )['total_price'] or 0

        return render(request, self.template_name, {"form": form, "buy": buy, "total_buy_price": total_buy_price, 'customer': customer, "pets": pets, "transaction": transaction,"total":total})


@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(LoginRequiredMixin, View):
    template_name = 'customer/edit_profile.html'

    def get(self, request):
        form = UserUpdateForm(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
        return render(request, self.template_name, {'form': form})


@login_required
def change_pass(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Password changed Successfully')
            update_session_auth_hash(request, form.user)

            mail_subject = 'Password Change'
            message = render_to_string('customer/pass_change_mail.html', {
                'user': request.user
            })
            to_email = request.user.email
            send_email = EmailMultiAlternatives(
                mail_subject, '', to=[to_email])
            send_email.attach_alternative(message, "text/html")
            send_email.send()
            return redirect('profile')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'customer/change_pass.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, "Logout successfully")
    return redirect('login')

customer/templates/customer/admin_home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Admin Home</title>
{% endblock title %}
{% block content %}
{% load humanize %}
<section class="container">
  <button id="toggleAddPet" class="btn btn-primary mt-4 mx-5">Show All Pets</button>
    <div id="all-pet" class="all-pet" style="display: none;">
      
            <h1 class="text-center my-4">Total Pets : {{pets |length}}</h1>
           <table class="table table-bordered">
  <thead>
    <tr>  
      <th scope="col">ID</th>
      <th scope="col">Photo</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Price</th>
      <th scope="col">Availability</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for i in pets %}
    <tr>
      <th scope="row">{{i.id}}</th>
      <td><a href="{% url 'edit_pet' i.id %}"><img class="rounded-circle" src="{{ i.image.url }}" style="width: 70px; height: 50px;" alt=""></a></td>
      <td>{{i.name}}</td>
      <td>
        {% for category in i.category.all %}
          {{ category.name }}
          {% if not forloop.last %}, {% endif %}
        {% endfor %}
      </td>
      <td>{{i.price}}</td>
      <td>{{i.availability}}</td>
      
      <td>
        <a class="btn btn-danger" href="{% url 'pet_delete' i.id %}">Delete</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

        </div>

    <!-- transaction  -->

<!-- Report  -->


<div class=" my-5">
  <h1 class="text-center pb-4">Transaction Report</h1>
  <hr />

  <form method="post" action="{% url 'admin_home' %}" class="d-flex justify-content-center mb-4">
    {% csrf_token %}
    <div class="input-group">
        <label for="start_date" class="input-group-text">From:</label>
        <input type="date" class="form-control" id="start_date" name="start_date" />
    </div>

    <div class="input-group mx-2">
        <label for="end_date" class="input-group-text">To:</label>
        <input type="date" class="form-control" id="end_date" name="end_date" />
    </div>

    <div class="">
        <button type="submit" class="btn btn-primary  px-4 fs-4">Filter</button>
    </div>
  </form>

  <table class="table table-bordered table-hover">
    <thead class="text-white text-center">
      <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Name</th>
        <th>Transaction Type</th>
        <th>Amount</th>
        <th>Balance After Transaction</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in object_list %}
      <tr>
        <td>{{transaction.id}}</td>
        <td>{{ transaction.timestamps|date:"F d, Y h:i A" }}</td>
        <td>{{ transaction.customer.user.username }}</td>
        <td class="text-center">
          <span class="badge bg-success">
            {{ transaction.get_transaction_type_display }}
          </span>
        </td>
        <td class="text-center">${{ transaction.amount|floatformat:2|intcomma }}</td>
        <td class="text-center">${{ transaction.balance_after_transaction|floatformat:2|intcomma }}</td>
      </tr>
      {% endfor %}
      <tr class="bg-dark text-white text-end">
        <th colspan="5">Total Transaction :</th>
        <th class="text-center">${{ total|floatformat:2|intcomma }}</th>
      </tr>
    </tbody>
  </table>
</div>

    </div>

</section>
    <script>
    document.getElementById('toggleAddPet').addEventListener('click', function () {
        var allPetDiv = document.getElementById('all-pet');
        allPetDiv.style.display = (allPetDiv.style.display === 'none') ? 'block' : 'none';
    });
</script>
{% endblock content %}

customer/templates/customer/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Change Password</title>
{% endblock title %}
{% block content %}

<div class="container" style="height: 100vh;">
  <h1 class="text-center text-info my-5">Change Your Password Here</h1>
<div class="col-8 m-auto shadow-lg p-5 rounded-5" >
  
  <form action="" method="post" class="w-50 m-auto" novalidate>
    
        <!-- {{form | crispy}} -->
        {% csrf_token %}
        {% if form.non_field_errors %}
          {% for er in form.non_field_errors %}
          <p class="bg-danger text-white p-3">{{er}}</p>
          {% endfor %}
        {% endif %}

        {% for fm in form %}
        {{fm.label_tag}}
        {{fm}}
        {{fm.errors | striptags}}
        {% endfor %}
        <br>
        <input class="btn btn-primary my-2" type="submit" value="Submit">
    </form>
</div>
</div>
{% endblock content %}

customer/templates/customer/confirm_mail.html
<div>
<h3>Thanks for crating an account on out platform.</h3>
<p>Please click the below link to verify your account</p>
    <p>
        Confirmation Link: <a target="_blank" href="{{confirm_link}}">{{confirm_link}}</a>
    </p>
</div>

customer/templates/customer/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
<title>Edit Profile</title>
{% endblock title %}
{% block content %}

    <div class="container h-100">
    <div class="col-md-6 mx-auto badge-info text-center p-2 badge-pill ">
        <h1 class="text-info">User Data Update Form</h1>
    </div>
    <hr>
    {% if form.non_field_errors %}
          {% for er in form.non_field_errors %}
          <p class="bg-danger text-white p-3">{{er}}</p>
          {% endfor %}
        {% endif %}
    <div class="row shadow-lg p-5 mb-5 rounded-5">
        <div class="col-md-10 mx-auto">
            <form class="row g-4" method="POST">
                {% csrf_token %}
                
                <div class="col-md-6">
                    {{form.first_name|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.last_name|as_crispy_field}}
                </div>
                
                <div class="col-md-6">
                    {{form.phone|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.gender|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.street_address|as_crispy_field}}
                </div>
                <div class="col-md-6">
                    {{form.city|as_crispy_field}}
                </div>

                <div class="col-md-6">  
                    {{form.country|as_crispy_field}}
                </div>
                <div class="col-md-6">  
                    {{form.image|as_crispy_field}}
                </div>
                
            
                <div class="col-md-12 my-3 ">
            
                    <div class="d-grid gap-2 col-4 mx-auto d-block">
                        <button class="btn btn-primary" type="submit">Submit</button>
                        <button class="btn btn-primary" type="reset">Reset</button>
                    </div>
                </div>
            </form>
        </div>
        
    </div>

</div>
{% endblock content %}

customer/templates/customer/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
  <title>Login</title>
{% endblock title %}

{% block content %}
  <div class="container m-auto" style="height: 100vh;">
    <h1 class="text-center text-info my-5">Login</h1>
    
    <div class="row d-flex justify-content-center align-items-center mt-5">
      <div class="col-sm-8 mb-3 mb-sm-0">
        <div class="card p-5 shadow-lg rounded-5  login">
          <div class="card-body d-flex justify-content-around align-items-center">
            <div class="col-md-4">
              <img src="{% static 'img/user4.png' %}" class="img-fluid rounded w-75 h-100" alt="...">
            </div>
            <div class="col-md-6">
              <h5 class="card-title mt-0"> 
                <form action="" method="post" id="loginForm" class="w-100 m-auto" novalidate>
                  <!-- {{form | crispy}} -->
                  {% csrf_token %}
                  {% if form.non_field_errors %}
                    {% for er in form.non_field_errors %}
                      <p class="bg-danger text-white p-3">{{er}}</p>
                    {% endfor %}
                  {% endif %}

                  {% for fm in form %}
                    {{fm.label_tag}}
                    {{fm}}
                    {{fm.errors | striptags}}
                  {% endfor %}
                  <br>
                  
                  <input class="btn btn-primary my-2 text-center" type="submit" value="Login">
                  <br>
                  <small>You don't have an account <a href="{% url 'register' %}">Register</a></small>
                  <button class="btn btn-primary my-2 text-center" type="button" onclick="fillDemo('user')">Demo User</button>
                  <button class="btn btn-primary my-2 text-center" type="button" onclick="fillDemo('admin')">Demo Admin</button>
                </form>
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  
  <script>
    function fillDemo(type) {
      const form = document.getElementById('loginForm');
      if (type === 'user') {
        form.username.value = 'mowuj';
        form.password.value = 'A@san1122';
      } else if (type === 'admin') {
        form.username.value = 'admin';
        form.password.value = '12345';
      }
    }
  </script>

{% endblock content %}

customer/templates/customer/pass_change_email.html
<h3>Hello {{user.first_name}} {{user.last_name}}</h3>

<p>Your Successfully Change User Password</p>

<p>Thanks for Stay with us</p>
<p>PET FAIR BD</p>

customer/templates/customer/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
<title>Profile</title>
{% endblock title %}
{% block content %}
{% load humanize %}
<div class="my-5 mx-4">
    <h1 class="text-center text-info">Profile</h1>

    <div class="d-md-flex">
        <div class="profile-left col-md-3">
        <div class="card shadow-lg rounded-5 p-2" style="width: 18rem;">
  <img src="{{customer.image.url}}" class="card-img-top img-thumbnail" alt="...">
  <div class="card-body">
    <h3 class="card-title">{{customer}}</h3>
    <h6 class="card-title">Full Name: {{customer.user.first_name}} {{customer.user.last_name}}</h6>
    <h6 class="card-title">ID: {{customer.id}}</h6>
    <h6 class="card-title">Phone{{customer.phone}}</h6>
    <p class="card-title">Street: {{customer.street_address}}</p>
    <p class="card-title">City: {{customer.city}}</p>
    <p class="card-title">Country: {{customer.country}}</p>
  </div>
</div>
    </div>
    <div class="profile-right col-md-9">
      <button id="toggleSellPet" class="btn btn-primary mt-4 mx-2 active">Sell Pet</button>
            <button id="toggleBuyPet" class="btn btn-secondary mt-4 mx-2">Buy Pet</button>
            <button id="toggleTransaction" class="btn btn-info mt-4 mx-2">Transaction</button>
        <div class="sell-pet" id="sellPetSection">
            <h1 class="text-center my-4">My Sell Report</h1>
            <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col" class="text-center">ID</th>
      <th scope="col" class="text-center">Image</th>
      <th scope="col" class="text-center">Name</th>
      <th scope="col" class="text-center">Category</th>
      <th scope="col" class="text-center">Price</th>
      <th scope="col" class="text-center">Availability</th>
      <th scope="col" class="text-center">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for i in pets %}
    <th scope="row" class="text-center">{{i.id}}</th>
    <td class="text-center"><a class="" href="{% url 'edit_pet' i.id %}"><img class="rounded-circle" src="{{ i.image.url }}" style="width: 60px; height: 45px;" alt=""></a></td>
      <td class="text-center">{{i.name}}</td>
      <td class="text-center">{% for category in i.category.all %}
    {{ category.name }}
    {% if not forloop.last %}, {% endif %}
  {% endfor %}</td>
      <td class="text-center">{{i.price}}</td>
      <td class="text-center">{{i.availability}}</td>
      
      <td class="text-center">
        
        <a class="btn btn-danger" href="{% url 'pet_delete' i.id %}">Delete</a>
      </td>
      {% endfor %}
    </tr>
    
    
  </tbody>
</table>
        </div>
        <div class="buy-pet" id="buyPetSection" style="display: none;">

          <h1 class="text-center my-4">My Buying Report</h1>
            <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col" class="text-center">ID</th>
      <th scope="col" class="text-center">Image</th>
      <th scope="col" class="text-center">Name</th>
      <th scope="col" class="text-center">Type</th>
      <th scope="col" class="text-center">Price</th>      
      <th scope="col" class="text-center">Balance After Buy</th>
      
    </tr>
  </thead>
  <tbody>
    {% for i in buy %}
      <tr>
        <th scope="row" class="text-center">{{i.id}}</th>
        <td class="text-center"><img class="rounded-circle" src="{{ i.pet.image.url }}" style="width: 60px; height: 45px;" alt=""></td>
        <td class="text-center">{{i.pet.name}}</td>
        <td class="text-center">{{i.get_transaction_type_display}}</td>
        <td class="text-center">{{i.amount}}</td>
        <td class="text-center">{{i.balance_after_transaction}}</td>
        
      </tr>
    {% endfor %}
    <tr>
            <td colspan="4"></td>
            <td class="text-center"><strong>Total Buying Price:</strong></td>
            <td colspan="1" class="text-center"><b>${{ total_buy_price|floatformat:2|intcomma }}</b> </td>
          </tr>
  </tbody>
</table>

        </div>
        <div class="transaction" id="transactionSection" style="display: none;">

          <h1 class="text-center my-4">Total Transaction Report</h1>
            <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col" class="text-center">ID</th>
      <th scope="col" class="text-center">Date</th>
      <th scope="col" class="text-center">Type</th>
      <th scope="col" class="text-center">Amount</th>
      <th scope="col" class="text-center">Balance After Buy</th>
    </tr>
  </thead>
  <tbody>
    {% for i in transaction %}
      <tr>
        <th scope="row" class="text-center">{{i.id}}</th>
        <td class="text-center">{{ i.timestamps|date:"F d, Y h:i A" }}</td>
        <td class="text-center">{{i.get_transaction_type_display}}</td>
        <td class="text-center">{{i.amount}}</td>
        <td class="text-center">{{i.balance_after_transaction}}</td>
        
      </tr>
    {% endfor %}
    <tr>
            <td colspan="3"></td>
            <td class="text-center"><strong>Total Transaction:</strong></td>
            <td colspan="1" class="text-center"><b>${{ total|floatformat:2|intcomma }}</b> </td>
          </tr>
  </tbody>
</table>

        </div>
    </div>
    </div>
</div>

<script>
    document.getElementById('toggleSellPet').addEventListener('click', function () {
        document.getElementById('sellPetSection').style.display = 'block';
        document.getElementById('buyPetSection').style.display = 'none';
        document.getElementById('transactionSection').style.display = 'none';
    });

    document.getElementById('toggleBuyPet').addEventListener('click', function () {
        document.getElementById('sellPetSection').style.display = 'none';
        document.getElementById('buyPetSection').style.display = 'block';
        document.getElementById('transactionSection').style.display = 'none';
    });

    document.getElementById('toggleTransaction').addEventListener('click', function () {
        document.getElementById('sellPetSection').style.display = 'none';
        document.getElementById('buyPetSection').style.display = 'none';
        document.getElementById('transactionSection').style.display = 'block';
    });
</script>
{% endblock content %}